#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    ALTER USER "$POSTGRES_USER" WITH PASSWORD '$POSTGRES_PASSWORD';

    \c "$POSTGRES_DB";

    CREATE SCHEMA IF NOT EXISTS auth AUTHORIZATION "$POSTGRES_USER";
    CREATE SCHEMA IF NOT EXISTS cadastro AUTHORIZATION "$POSTGRES_USER";

    ALTER DATABASE "$POSTGRES_DB" SET search_path TO auth, cadastro, public;

    ALTER SCHEMA auth OWNER TO "$POSTGRES_USER";
    ALTER SCHEMA cadastro OWNER TO "$POSTGRES_USER";
EOSQL
